networks:
  monitoring:
    driver: bridge

services:
  app:
    image: log-generator:latest
    container_name: app
    ports:
      - "8080:8080"
    command:
      - ./gradlew publish
    volumes:
      - ./.logs:/home/app/logs
    networks:
      - monitoring

  loki:
    image: grafana/loki:3.1.1
    container_name: loki
    ports:
      - "3100:3100"
    command:
      -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - ./.logs:/var/log/app
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command:
      -config.file=/etc/promtail/config.yml
    networks:
      - monitoring
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./.grafana-storage:/var/lib/grafana
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/alert.yaml:/etc/grafana/provisioning/alerting/alert.yaml
      - ./grafana/500-errors-dashboard.json:/usr/share/grafana/500-errors-dashboard.json
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=dev.ideascale@gmail.com
      - GF_SMTP_PASSWORD=cndk vgjy vsro zjqk
      - GF_SMTP_FROM_ADDRESS=noreply@gmail.com
    networks:
      - monitoring
    depends_on:
      - loki
      - promtail